
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.20.52.115:3306/ordermgr?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: evoa_dev
    password: Goodsense@2020
    type: com.zaxxer.hikari.HikariDataSource
xxl:
  job:
    accessToken:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: xxl-job-executor-athena
      address: http://127.0.0.1:8080/xxl-job-admin
      ip:
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1
      port: 9999

logging.level.com.demo.mapper: debug
server:
  port: 8088
mybatis:
  mapper-locations: classpath*:mybatis/**/*.xml
  type-aliases-package: com.cookie.mybatis.model


timeout:
  betting: 20
  gaming: 30
  payout: 40
  halt: 60
  ad: "222.443.321.41,223.443.22.321"
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql